default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: db
  username: postgres
  password: postgres

development:
  <<: *default
  database: pottode_development
  username: postgres
  password: password
test:
  <<: *default
  database: pottode_test

production:
  <<: *default
  database: pottode_production
  username: myapp
  password: <%= ENV["POTTODE_DATABASE_PASSWORD"] %>
  adapter: postgresql
  encoding: unicode
  pool: 5
